### ISSUE TITLE
Error in page 142

### ISSUE THREAD

**Issue by DavidePastore** [azat-co/rpjs#8]
Second ```getMessages()``` calling shouldn't have parameters.

**Comment by SOSANA** [comment]
David,

having a heck of a time debuggin the chat rest api db store(mongo https://github.com/azat-co/rpjs/tree/master/mongo).

By any chance do you have a working copy of this?

**Comment by DavidePastore** [comment]
What is your error? Maybe @azat-co is the right person to help you.

**Comment by SOSANA** [comment]
@DavidePastore I figured it out. Outdated mongodb driver version. Mongodb v2.6.* and above has new method to connect to mongodb drivers.

I updated my issue with how I fixed the problem.
